import React from 'react';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: 20,
  },
  textInput: {
    width: 300,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'black',
    borderRadius: 10,
    padding: 10,
    fontSize: 16,
    margin: 10,
    color: 'black',
    backgroundColor: 'white',
  },
  title: {
    padding: 10,
    textAlign: 'center',
    color: 'black',
    fontSize: 30,
    borderRadius: 20,
    fontWeight: 'bold',
  },
  subTitle: {
    padding: 10,
    margin: 10,
    textAlign: 'center',
    color: 'black',
    fontSize: 22,
    borderRadius: 20,
  },
  cardList: {
    padding: 10,
    alignItems: 'center',
  },
  btnSub: {
    backgroundColor: '#0275d8',
    width: 300,
    alignItems: 'center',
    padding: 10,
    marginBottom: 20,
    borderRadius: 10,
  },
  btnTxt: {
    fontSize: 16,
    color: 'white',
  },
  plainText: {
    alignSelf: 'flex-start',
    fontSize: 18,
    padding: 5,
    fontWeight: '700',
  },
  infoText: {
    fontSize: 21,
    margin: 10,
    marginBottom: 20,
    padding: 10,
  },
  greetText: {
    textAlign: 'center',
    backgroundColor: '#7AD7F0',
  },
  cardContainer: {
    flex: 1,
    justifyContent: 'center',
    borderRadius: 20,
    padding: 10,
    margin: 50,
    maxHeight: 400,
    minWidth: 320,
  },
  card: {
    flex: 1,
    width: 300,
    minHeight: 100,
    padding: 10,
    margin: 10,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 20,
  },
  card1: {
    backgroundColor: '#957fb3',
  },
  card2: {
    backgroundColor: '#6bb36b',
  },
  cardTitle: {
    fontSize: 23,
    fontWeight: '700',
  },
  label: {
    flex: 1,
    paddingTop: 60,
    justifyContent: 'flex-end',
    textAlign: 'center',
    fontSize: 21,
    fontFamily: 'System',
    color: 'white',
    backgroundColor: 'transparent',
  },
  newContainer: {
    flex: 1,
    borderWidth: 1,
    margin: 10,
    padding: 10,
    width: 270,
    maxHeight: 300,
    borderRadius: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#36c26c',
  },
  mainText: {
    padding: 10,
    color: 'white',
    fontSize: 21,
    textAlign: 'center',
  },
  normalText: {
    color: 'white',
    fontSize: 16,
    textAlign: 'center',
  },
  textContent: {
    flex: 1,
    minHeight: 200,
    maxHeight: 300,
    width: 300,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    margin: 10,
    padding: 10,
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: '#edeeef',
  },
  content: {
    fontSize: 20,
    fontWeight: '700',
  },
});

export default styles;
